apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-serviceaccount-devops
  namespace: admin
subjects:
- kind: ServiceAccount
  name: devops-kubernetes-svc
  namespace: admin
roleRef:
  kind: Role
  name: role-for-serviceaccount-devops
  apiGroup: rbac.authorization.k8s.io